CHSNsqRspInfoField = {
    "ErrorID": "int",
    "ErrorMsg": "string",
}

CHSNsqReqUserLoginField = {
    "AccountID": "string",
    "Password": "string",
    "UserApplicationType": "char",
    "UserApplicationInfo": "string",
    "MacAddress": "string",
    "IPAddress": "string",
}

CHSNsqRspUserLoginField = {
    "BranchID": "int",
    "AccountID": "string",
    "UserName": "string",
    "TradingDay": "int",
    "PreTradingDay": "int",
    "BillConfirmFlag": "char",
    "SessionID": "int",
    "UserApplicationType": "char",
    "UserApplicationInfo": "string",
    "RiskLevel": "string",
    "LastMacAddress": "string",
    "LastIPAddress": "string",
    "LastLoginTime": "int",
    "CZCETime": "int",
    "DCETime": "int",
    "SHFETime": "int",
    "CFFEXTime": "int",
    "INETime": "int",
}

CHSNsqReqDepthMarketDataField = {
    "ExchangeID": "string",
    "InstrumentID": "string",
}

CHSNsqReqQryDepthMarketDataField = {
    "ExchangeID": "string",
    "InstrumentID": "string",
}

CHSNsqReqFutuDepthMarketDataField = {
    "ExchangeID": "string",
    "InstrumentID": "string",
}

CHSNsqFutuDepthMarketDataField = {
    "TradingDay": "int",
    "InstrumentID": "string",
    "ExchangeID": "string",
    "LastPrice": "double",
    "PreSettlementPrice": "double",
    "PreClosePrice": "double",
    "OpenPrice": "double",
    "HighestPrice": "double",
    "LowestPrice": "double",
    "TradeVolume": "int",
    "TradeBalance": "double",
    "OpenInterest": "int",
    "ClosePrice": "double",
    "SettlementPrice": "double",
    "UpperLimitPrice": "double",
    "LowerLimitPrice": "double",
    "UpdateTime": "int",
    "BidPrice": "string",
    "AskPrice": "string",
    "BidVolume": "string",
    "AskVolume": "string",
    "AveragePrice": "double",
    "PreOpenInterest": "int",
    "InstrumentTradeStatus": "char",
}

CHSNsqFutuInstrumentStaticInfoField = {
    "ExchangeID": "string",
    "InstrumentID": "string",
    "InstrumentName": "string",
    "SecurityType": "char",
    "PreClosePrice": "double",
    "UpperLimitPrice": "double",
    "LowerLimitPrice": "double",
    "PriceTick": "double",
    "BuyVolumeUnit": "int",
    "SellVolumeUnit": "int",
    "TradeDate": "int",
}

CHSNsqReqSecuDepthMarketDataField = {
    "ExchangeID": "string",
    "InstrumentID": "string",
}

CHSNsqSecuDepthMarketDataField = {
    "ExchangeID": "string",
    "InstrumentID": "string",
    "LastPrice": "double",
    "PreClosePrice": "double",
    "OpenPrice": "double",
    "HighPrice": "double",
    "LowPrice": "double",
    "ClosePrice": "double",
    "UpperLimitPrice": "double",
    "LowerLimitPrice": "double",
    "TradeDate": "int",
    "UpdateTime": "int",
    "TradeVolume": "int",
    "TradeBalance": "double",
    "AveragePrice": "double",
    "BidPrice": "string",
    "AskPrice": "string",
    "BidVolume": "string",
    "AskVolume": "string",
    "TradesNum": "int",
    "InstrumentTradeStatus": "char",
    "TotalBidVolume": "int",
    "TotalAskVolume": "int",
    "MaBidPrice": "double",
    "MaAskPrice": "double",
    "MaBondBidPrice": "double",
    "MaBondAskPrice": "double",
    "YieldToMaturity": "double",
    "IOPV": "double",
    "EtfBuycount": "int",
    "EtfSellCount": "int",
    "EtfBuyVolume": "int",
    "EtfBuyBalance": "double",
    "EtfSellVolume": "int",
    "EtfSellBalance": "double",
    "TotalWarrantExecVolume": "int",
    "WarrantLowerPrice": "double",
    "WarrantUpperPrice": "double",
    "CancelBuyNum": "int",
    "CancelSellNum": "int",
    "CancelBuyVolume": "int",
    "CancelSellVolume": "int",
    "CancelBuyValue": "double",
    "CancelSellValue": "double",
    "TotalBuyNum": "int",
    "TotalSellNum": "int",
    "DurationAfterBuy": "int",
    "DurationAfterSell": "int",
    "BidOrdersNum": "int",
    "AskOrdersNum": "int",
    "PreIOPV": "double",
    "ChannelNo": "int",
    "BondLastAuctionPrice": "double",
    "BondAuctionVolume": "int",
    "BondAuctionBalance": "double",
    "BondLastTradeType": "char",
}

CHSNsqSecuDepthMarketDataPlusField = {
    "ChannelNo": "int",
    "ExchangeID": "string",
    "InstrumentID": "string",
    "LastPrice": "double",
    "OpenPrice": "double",
    "HighPrice": "double",
    "LowPrice": "double",
    "TradeDate": "int",
    "UpdateTime": "int",
    "TradeVolume": "int",
    "TradeBalance": "double",
    "TotalBidVolume": "int",
    "TotalAskVolume": "int",
    "TradesNum": "int",
    "BidPrice": "string",
    "BidVolume": "string",
    "AskPrice": "string",
    "AskVolume": "string",
}

CHSNsqSecuDepthMarketDataPlusStopNoticeField = {
    "ChannelNo": "int",
}

CHSNsqReqSecuTransactionRebuildField = {
    "ExchangeID": "string",
    "ChannelNo": "int",
    "BeginSeqNo": "int",
    "EndSeqNo": "int",
    "RebuildType": "char",
}

CHSNsqSecuATPMarketDataField = {
    "ExchangeID": "string",
    "InstrumentID": "string",
    "PreClosePrice": "double",
    "ClosePrice": "double",
    "TradeDate": "int",
    "UpdateTime": "int",
    "InstrumentTradeStatus": "char",
    "TradeVolume": "int",
    "TradeBalance": "double",
    "TradesNum": "int",
    "TotalBidVolume": "int",
    "TotalAskVolume": "int",
    "CancelBuyNum": "int",
    "CancelSellNum": "int",
    "CancelBuyVolume": "int",
    "CancelSellVolume": "int",
    "BidPrice1": "double",
    "AskPrice1": "double",
    "BidVolume1": "int",
    "AskVolume1": "int",
    "ChannelNo": "int",
}

CHSNsqSecuTransactionTradeDataField = {
    "ExchangeID": "string",
    "InstrumentID": "string",
    "TransFlag": "int",
    "SeqNo": "int",
    "ChannelNo": "int",
    "TradeDate": "int",
    "TransactTime": "int",
    "TrdPrice": "double",
    "TrdVolume": "int",
    "TrdMoney": "double",
    "TrdBuyNo": "int",
    "TrdSellNo": "int",
    "TrdBSFlag": "char",
    "BizIndex": "int",
}

CHSNsqSecuTransactionEntrustDataField = {
    "ExchangeID": "string",
    "InstrumentID": "string",
    "TransFlag": "int",
    "SeqNo": "int",
    "ChannelNo": "int",
    "TradeDate": "int",
    "TransactTime": "int",
    "OrdPrice": "double",
    "OrdVolume": "int",
    "OrdSide": "char",
    "OrdType": "char",
    "OrdNo": "int",
    "BizIndex": "int",
}

CHSNsqSecuInstrumentStaticInfoField = {
    "ExchangeID": "string",
    "InstrumentID": "string",
    "InstrumentName": "string",
    "SecurityType": "char",
    "PreClosePrice": "double",
    "UpperLimitPrice": "double",
    "LowerLimitPrice": "double",
    "PriceTick": "double",
    "BuyVolumeUnit": "int",
    "SellVolumeUnit": "int",
    "TradeDate": "int",
}

CHSNsqReqOptDepthMarketDataField = {
    "ExchangeID": "string",
    "InstrumentID": "string",
}

CHSNsqOptInstrumentStaticInfoField = {
    "ExchangeID": "string",
    "InstrumentID": "string",
    "InstrumentTradeID": "string",
    "InstrumentName": "string",
    "SecurityType": "char",
    "UnderlyingInstrID": "string",
    "OptionsType": "char",
    "ExerciseStyle": "char",
    "ContractMultiplierUnit": "int",
    "ExercisePrice": "double",
    "StartDate": "int",
    "EndDate": "int",
    "ExerciseDate": "int",
    "DeliveryDate": "int",
    "ExpireDate": "int",
    "TotalLongPosition": "int",
    "PreClosePrice": "double",
    "PreSettlPrice": "double",
    "UnderlyingClosePrice": "double",
    "UpperLimitPrice": "double",
    "LowerLimitPrice": "double",
    "MarginUnit": "double",
    "MarginRatioParam1": "double",
    "MarginRatioParam2": "double",
    "VolumeMultiple": "int",
    "MinLimitOrderVolume": "int",
    "MaxLimitOrderVolume": "int",
    "MinMarketOrderVolume": "int",
    "MaxMarketOrderVolume": "int",
    "PriceTick": "double",
    "TradeDate": "int",
}

CHSNsqOptDepthMarketDataField = {
    "ExchangeID": "string",
    "InstrumentID": "string",
    "LastPrice": "double",
    "PreClosePrice": "double",
    "OpenPrice": "double",
    "HighPrice": "double",
    "LowPrice": "double",
    "ClosePrice": "double",
    "PreOpenInterest": "int",
    "OpenInterest": "int",
    "PreSettlementPrice": "double",
    "SettlementPrice": "double",
    "UpperLimitPrice": "double",
    "LowerLimitPrice": "double",
    "PreDelta": "double",
    "CurDelta": "double",
    "TradeDate": "int",
    "UpdateTime": "int",
    "TradeVolume": "int",
    "TradeBalance": "double",
    "AveragePrice": "double",
    "BidPrice": "string",
    "AskPrice": "string",
    "BidVolume": "string",
    "AskVolume": "string",
    "TradesNum": "int",
    "InstrumentTradeStatus": "char",
    "OpenRestriction": "string",
    "AuctionPrice": "double",
    "AuctionVolume": "int",
    "LastEnquiryTime": "int",
    "LeaveQty": "int",
    "ChannelNo": "int",
}

CHSNsqReqHktDepthMarketDataField = {
    "ExchangeID": "string",
    "InstrumentID": "string",
}

CHSNsqHktInstrumentStaticInfoField = {
    "ExchangeID": "string",
    "InstrumentID": "string",
    "InstrumentName": "string",
    "SecurityType": "char",
    "PreClosePrice": "double",
    "BuyVolumeUnit": "int",
    "SellVolumeUnit": "int",
    "TradeDate": "int",
}

CHSNsqHktDepthMarketDataField = {
    "ExchangeID": "string",
    "InstrumentID": "string",
    "LastPrice": "double",
    "PreClosePrice": "double",
    "HighPrice": "double",
    "LowPrice": "double",
    "NomianlPrice": "double",
    "TradeDate": "int",
    "UpdateTime": "int",
    "TradeVolume": "int",
    "TradeBalance": "double",
    "BidPrice": "string",
    "AskPrice": "string",
    "BidVolume": "string",
    "AskVolume": "string",
    "InstrumentTradeStatus": "char",
    "BoardLotOrderBidLimit": "char",
    "BoardLotOrderAskLimit": "char",
    "OddLotOrderBidLimit": "char",
    "OddLotOrderAskLimit": "char",
    "ChannelNo": "int",
}

CHSNsqBondTransactionTradeDataField = {
    "ExchangeID": "string",
    "InstrumentID": "string",
    "TransFlag": "int",
    "SeqNo": "int",
    "ChannelNo": "int",
    "TradeDate": "int",
    "TransactTime": "int",
    "TrdPrice": "double",
    "TrdVolume": "int",
    "TrdBuyNo": "int",
    "TrdSellNo": "int",
    "TrdBSFlag": "char",
    "TradeType": "char",
    "SettlPeriod": "unsigned short",
    "SettlType": "unsigned short",
}

CHSNsqBondTransactionEntrustDataField = {
    "ExchangeID": "string",
    "InstrumentID": "string",
    "TransFlag": "int",
    "SeqNo": "int",
    "ChannelNo": "int",
    "TradeDate": "int",
    "TransactTime": "int",
    "OrdPrice": "double",
    "OrdVolume": "int",
    "OrdSide": "char",
    "OrdType": "char",
    "TradeType": "char",
    "SettlPeriod": "unsigned short",
    "SettlType": "unsigned short",
    "QuoteID": "string",
    "MemberID": "string",
    "InvestorType": "string",
    "InvestorID": "string",
    "TraderCode": "string",
}

CHSNsqSecuTransactionDataField = {
    "LatestSeqNo": "int",
    "TransType": "char",
}

